// Auto-generated by ApiResourceTyper
// Generated at: 2025-06-30 04:15:56

export interface DepartemenIndexType {
  id: number;
  nama_departemen: string;
  created_at: Date;
  updated_at: Date;
}

export interface DepartemenIndexTypeResponse {
  data: DepartemenIndexType;
}

export interface DepartemenIndexTypeCollection {
  data: DepartemenIndexType[];
  links?: {
    first: string;
    last: string;
    prev: string | null;
    next: string | null;
  };
  meta?: {
    current_page: number;
    last_page: number;
    per_page: number;
    total: number;
  };
}
