// Auto-generated by ApiResourceTyper
// Generated at: 2025-06-30 04:53:30

export interface JabatanIndexType {
  id: number;
  nama_jabatan: string;
  created_at: Date;
  updated_at: Date;
}

export interface JabatanIndexTypeResponse {
  data: JabatanIndexType;
}

export interface JabatanIndexTypeCollection {
  data: JabatanIndexType[];
  links?: {
    first: string;
    last: string;
    prev: string | null;
    next: string | null;
  };
  meta?: {
    current_page: number;
    last_page: number;
    per_page: number;
    total: number;
  };
}
