// Auto-generated by ApiResourceTyper
// Generated at: 2025-06-30 03:35:43

export interface KaryawanStoreType {
  message: string;
  errors: object;
}

export interface KaryawanStoreTypeResponse {
  data: KaryawanStoreType;
}

export interface KaryawanStoreTypeCollection {
  data: KaryawanStoreType[];
  links?: {
    first: string;
    last: string;
    prev: string | null;
    next: string | null;
  };
  meta?: {
    current_page: number;
    last_page: number;
    per_page: number;
    total: number;
  };
}
