// Auto-generated by ApiResourceTyper
// Generated at: 2025-06-30 04:00:23

export interface KaryawanIndexType {
  id: number;
  id_jabatan: number;
  id_departemen: number;
  nama_lengkap: string;
  nik_ktp: string;
  npwp: string;
  status_ptkp: string;
  tanggal_bergabung: Date;
  gaji_pokok: string;
  nomor_rekening: string;
  nama_bank: string;
  status_kepegawaian: string;
  is_active: number;
  created_at: Date;
  updated_at: Date;
  jabatan: object;
  departemen: object;
}

export interface KaryawanIndexTypeResponse {
  data: KaryawanIndexType;
}

export interface KaryawanIndexTypeCollection {
  data: KaryawanIndexType[];
  links?: {
    first: string;
    last: string;
    prev: string | null;
    next: string | null;
  };
  meta?: {
    current_page: number;
    last_page: number;
    per_page: number;
    total: number;
  };
}
