// Auto-generated by ApiResourceTyper
// Generated at: 2025-06-30 04:32:29

export interface Slip-gajiIndexType {
  id: number;
  id_payroll_run: number;
  id_karyawan: number;
  gaji_pokok: string;
  total_tunjangan: string;
  total_potongan: string;
  penghasilan_bruto: string;
  pph21_terpotong: string;
  total_iuran_bpjs_kesehatan: string;
  thp: string;
  detail_json: string;
  created_at: Date;
  updated_at: Date;
}

export interface Slip-gajiIndexTypeResponse {
  data: Slip-gajiIndexType;
}

export interface Slip-gajiIndexTypeCollection {
  data: Slip-gajiIndexType[];
  links?: {
    first: string;
    last: string;
    prev: string | null;
    next: string | null;
  };
  meta?: {
    current_page: number;
    last_page: number;
    per_page: number;
    total: number;
  };
}
